Repository CertainLach/jrsonnet, pull requests merged in 2022-11, with the labels that each got.

#89 feat: add intrinsics for numeric parsing
  crates/jrsonnet-stdlib/src/lib.rs
  crates/jrsonnet-stdlib/src/strings.rs
Labels: enhancement

#90 chore: remove int parsing functions from std.jsonnet
  crates/jrsonnet-stdlib/src/std.jsonnet
Labels: enhancement

#91 feat: implement builtins for trivial numeric functions
  crates/jrsonnet-stdlib/src/lib.rs
  crates/jrsonnet-stdlib/src/math.rs
  crates/jrsonnet-stdlib/src/std.jsonnet
Labels: enhancement

#92 fix: use correct parameter names for intrinsics
  crates/jrsonnet-stdlib/src/math.rs
  crates/jrsonnet-stdlib/src/strings.rs
Labels: bug

#94 Fix: Use variable names from jsonnet stdlib for is_x builtins
  crates/jrsonnet-stdlib/src/types.rs
Labels: enhancement, good first issue
